# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Çilem Karşıt
title: Bilgi ve Belge Yönetimi
phone: 0534 573 13 37
email: cilem105@gmail.com

# About Section
about_title: Hakkımda
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Merhaba, ben Çilem Karşıt. 1996 yılında Erzincan'da doğdum. Lisans eğitimimin bir kısmını Erzurum'da, Atatürk Üniversitesi, Bilgi ve Belge Yönetimi Bölümü'nde tamamladım.
  Bir kısmına da İstanbul Üniversitesi, Bilgi ve Belge Yönetimi bölümünde tamamladım. Eğitim hayatımda edindiğim bilgilerin üstüne her geçen gün yenilerini ekleyerek, süreklilik içinde kendimi geliştirmeye devam ediyorum.<br><br>
  <b>Genel yeteneklerim:</b> &nbsp; &nbsp; &nbsp; <mark>Yordam</mark> <mark>KOHA</mark> <mark>Sierra</mark> <mark>Web Tasarım</mark> <mark>Veri Tabanı</mark>
  <br><br>
  <b>Diller:</b> &nbsp; &nbsp; &nbsp; <mark>İNGİLİZCE &starf; &starf; &starf; &star; &star;</mark> <mark>ALMANCA &starf; &star; &star; &star; &star;</mark> <mark>OSMANLICA &starf; &starf; &starf; &star; &star;</mark>

# Projects Section
projects_title: Araştırmalarım

# Experience Section
experience_title: İş Tecrübelerim

# Education Section
educaton_title: Akademik Bilgilerim
  
# More Section
more_title: Sertifikalar ve Katılım Belgeleri
more_content: | # this will include new lines to allow paragraphs
 <ul>
    <li>Amerikan Dil Kültür Okulları A1, A2 Seviye İngilizce <strong>Sertifikası</strong></li>
    <li>İSMEK, Ofis Programları Kullanımı, Word, Excel ve Microsoft PowerPoint <strong>Sertifikası</strong></li>
    <li>İlber Ortaylı (Tarih Profesörü), Bilginin Gücü <strong>Sertifikası</strong></li>
    <li>Gençlik ve Spor Bakanlığı Damla Projesi Huzurevi Teması Gönüllü Çalışma, <strong>Katılım Belgesi</strong></li>
    <li>“Geleceğin İş Hayatı”, “İyi Hissetmeyi Seç”, “Neden Hepimiz Blok Flüt Çaldık?” Yaşamartı Zirve İstanbul, Erdem Aksakal, Ozanser Uğurlu, Burak Ünaldı, <strong>Katılım Belgesi</strong></li>
    <li>Erhan Ertürk (Haber Spikeri), “Etkili Konuşma ve Beden Dili” Yaşamartı Zirve İstanbul, <strong>Katılım Belgesi</strong></li>
    <li>“Çocukların Okuma Alışkanlığı” “Çocuk Kütüphaneleri” İstanbul Üniversitesi Bilgi ve Belge Yöneticileri Derneği, <strong>Katılım Belgesi</strong></li>
  </ul><br><br><br>
  
  <h2><strong>Referanslar</strong></h2>
  <p>Şule Yılmaz, Enka Okulları İlk Okul Kütüphane Görevlisi</p>
  <ul>
    <li>Telefon Numarası: 0532 361 32 08</li>
    <li>E-Posta: sule.yilmaz@enka.k12.tr</li>
  </ul>
  <p>Ümit Konya, İstanbul Üniversitesi Bilgi ve Belge Yönetimi, Bölüm Profesörü</p>
  <ul>
    <li>Telefon Numarası: 0535 415 01 97</li>
    <li>E-Posta: umitkonya@hotmail.com</li>
  </ul>
  <p>Özlem Bayrak, TC Cumhurbaşkanlığı Külliyesi Hadımköy Projesi Danışmanı</p>
  <ul>
    <li>Telefon Numarası: 0533 512 43 48</li>
  </ul>
  <p>Hatice Gülçur İnanç TC Cumhurbaşkanlığı Külliyesi Hadımköy Projesi Danışmanı</p>
   <ul>
    <li>Telefon Numarası: 0542 445 73 50 </li>
  </ul>

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
